(cl:in-package piper_msgs_srvs-srv)
(cl:export '(COMMAND-VAL
          COMMAND
          PARAM1-VAL
          PARAM1
          PARAM2-VAL
          PARAM2
          PARAM3-VAL
          PARAM3
          X-VAL
          X
          Y-VAL
          Y
          Z-VAL
          Z
          ROLL-VAL
          ROLL
          PITCH-VAL
          PITCH
          YAW-VAL
          YAW
          SUCCESS-VAL
          SUCCESS
          MESSAGE-VAL
          MESSAGE
          CUR_X-VAL
          CUR_X
          CUR_Y-VAL
          CUR_Y
          CUR_Z-VAL
          CUR_Z
          CUR_ROLL-VAL
          CUR_ROLL
          CUR_PITCH-VAL
          CUR_PITCH
          CUR_YAW-VAL
          CUR_YAW
          CUR_JOINT-VAL
          CUR_JOINT
))