# === Goal ===

uint8 command_type
uint8 HOME=0
uint8 MOVE_JOINTS=1
uint8 MOVE_TARGET=2
uint8 MOVE_TARGET_IN_EEF_FRAME=3
uint8 TELESCOPIC_END=4
uint8 ROTATE_END=5
uint8 MOVE_LINE=6
uint8 MOVE_BEZIER=7
uint8 MOVE_DECARTES=8
uint8 MOVE_TO_ZERO=9

# 通用位姿字段
float64 x
float64 y
float64 z
float64 roll
float64 pitch
float64 yaw

# 标准位姿字段
geometry_msgs/Pose pose
geometry_msgs/Point point
geometry_msgs/Quaternion quaternion
geometry_msgs/Pose[] waypoints

# 关节目标
float64[] joints

# 通用数值参数
float64[] values

---

# === Result ===

bool success
string message
int32 error_code

# 通用位姿字段
float64 cur_x
float64 cur_y
float64 cur_z
float64 cur_roll
float64 cur_pitch
float64 cur_yaw

# 标准位姿字段
geometry_msgs/Pose cur_pose
geometry_msgs/Point point
geometry_msgs/Quaternion quaternion
geometry_msgs/Pose[] waypoints

# 当前关节角列表
float64[] cur_joint

---

# === Feedback ===

string stage
float64 progress
string message

# 通用位姿字段
float64 cur_x
float64 cur_y
float64 cur_z
float64 cur_roll
float64 cur_pitch
float64 cur_yaw

# 标准位姿字段
geometry_msgs/Pose cur_pose
geometry_msgs/Point point
geometry_msgs/Quaternion quaternion
geometry_msgs/Pose[] waypoints

# 当前关节角列表
float64[] cur_joint
