# === Request ===

uint8 command_type
uint8 STOP=0

# 通用数值参数
float64[] values

---

# === Response ===

bool success
string message
int32 error_code

float64 cur_x
float64 cur_y
float64 cur_z
float64 cur_roll
float64 cur_pitch
float64 cur_yaw
float64[] cur_joint
