// Generated by gencpp from file piper_msgs_srvs/piper_cmdResponse.msg
// DO NOT EDIT!


#ifndef PIPER_MSGS_SRVS_MESSAGE_PIPER_CMDRESPONSE_H
#define PIPER_MSGS_SRVS_MESSAGE_PIPER_CMDRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace piper_msgs_srvs
{
template <class ContainerAllocator>
struct piper_cmdResponse_
{
  typedef piper_cmdResponse_<ContainerAllocator> Type;

  piper_cmdResponse_()
    : success(false)
    , message()
    , cur_x(0.0)
    , cur_y(0.0)
    , cur_z(0.0)
    , cur_roll(0.0)
    , cur_pitch(0.0)
    , cur_yaw(0.0)
    , cur_joint()  {
    }
  piper_cmdResponse_(const ContainerAllocator& _alloc)
    : success(false)
    , message(_alloc)
    , cur_x(0.0)
    , cur_y(0.0)
    , cur_z(0.0)
    , cur_roll(0.0)
    , cur_pitch(0.0)
    , cur_yaw(0.0)
    , cur_joint(_alloc)  {
  (void)_alloc;
    }



   typedef uint8_t _success_type;
  _success_type success;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _message_type;
  _message_type message;

   typedef double _cur_x_type;
  _cur_x_type cur_x;

   typedef double _cur_y_type;
  _cur_y_type cur_y;

   typedef double _cur_z_type;
  _cur_z_type cur_z;

   typedef double _cur_roll_type;
  _cur_roll_type cur_roll;

   typedef double _cur_pitch_type;
  _cur_pitch_type cur_pitch;

   typedef double _cur_yaw_type;
  _cur_yaw_type cur_yaw;

   typedef std::vector<double, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<double>> _cur_joint_type;
  _cur_joint_type cur_joint;





  typedef boost::shared_ptr< ::piper_msgs_srvs::piper_cmdResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::piper_msgs_srvs::piper_cmdResponse_<ContainerAllocator> const> ConstPtr;

}; // struct piper_cmdResponse_

typedef ::piper_msgs_srvs::piper_cmdResponse_<std::allocator<void> > piper_cmdResponse;

typedef boost::shared_ptr< ::piper_msgs_srvs::piper_cmdResponse > piper_cmdResponsePtr;
typedef boost::shared_ptr< ::piper_msgs_srvs::piper_cmdResponse const> piper_cmdResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::piper_msgs_srvs::piper_cmdResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::piper_msgs_srvs::piper_cmdResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::piper_msgs_srvs::piper_cmdResponse_<ContainerAllocator1> & lhs, const ::piper_msgs_srvs::piper_cmdResponse_<ContainerAllocator2> & rhs)
{
  return lhs.success == rhs.success &&
    lhs.message == rhs.message &&
    lhs.cur_x == rhs.cur_x &&
    lhs.cur_y == rhs.cur_y &&
    lhs.cur_z == rhs.cur_z &&
    lhs.cur_roll == rhs.cur_roll &&
    lhs.cur_pitch == rhs.cur_pitch &&
    lhs.cur_yaw == rhs.cur_yaw &&
    lhs.cur_joint == rhs.cur_joint;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::piper_msgs_srvs::piper_cmdResponse_<ContainerAllocator1> & lhs, const ::piper_msgs_srvs::piper_cmdResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace piper_msgs_srvs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::piper_msgs_srvs::piper_cmdResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::piper_msgs_srvs::piper_cmdResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::piper_msgs_srvs::piper_cmdResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::piper_msgs_srvs::piper_cmdResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::piper_msgs_srvs::piper_cmdResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::piper_msgs_srvs::piper_cmdResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::piper_msgs_srvs::piper_cmdResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "7e1b53476df714dd5d04f5cf9fe8e844";
  }

  static const char* value(const ::piper_msgs_srvs::piper_cmdResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x7e1b53476df714ddULL;
  static const uint64_t static_value2 = 0x5d04f5cf9fe8e844ULL;
};

template<class ContainerAllocator>
struct DataType< ::piper_msgs_srvs::piper_cmdResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "piper_msgs_srvs/piper_cmdResponse";
  }

  static const char* value(const ::piper_msgs_srvs::piper_cmdResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::piper_msgs_srvs::piper_cmdResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# 响应部分\n"
"bool success        # 执行是否成功\n"
"string message      # 返回消息\n"
"float64 cur_x       # 当前x坐标\n"
"float64 cur_y       # 当前y坐标\n"
"float64 cur_z       # 当前z坐标\n"
"float64 cur_roll    # 当前roll角\n"
"float64 cur_pitch   # 当前pitch角\n"
"float64 cur_yaw     # 当前yaw角\n"
"float64[] cur_joint # 当前各关节位置数组 \n"
;
  }

  static const char* value(const ::piper_msgs_srvs::piper_cmdResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::piper_msgs_srvs::piper_cmdResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.success);
      stream.next(m.message);
      stream.next(m.cur_x);
      stream.next(m.cur_y);
      stream.next(m.cur_z);
      stream.next(m.cur_roll);
      stream.next(m.cur_pitch);
      stream.next(m.cur_yaw);
      stream.next(m.cur_joint);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct piper_cmdResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::piper_msgs_srvs::piper_cmdResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::piper_msgs_srvs::piper_cmdResponse_<ContainerAllocator>& v)
  {
    s << indent << "success: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.success);
    s << indent << "message: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.message);
    s << indent << "cur_x: ";
    Printer<double>::stream(s, indent + "  ", v.cur_x);
    s << indent << "cur_y: ";
    Printer<double>::stream(s, indent + "  ", v.cur_y);
    s << indent << "cur_z: ";
    Printer<double>::stream(s, indent + "  ", v.cur_z);
    s << indent << "cur_roll: ";
    Printer<double>::stream(s, indent + "  ", v.cur_roll);
    s << indent << "cur_pitch: ";
    Printer<double>::stream(s, indent + "  ", v.cur_pitch);
    s << indent << "cur_yaw: ";
    Printer<double>::stream(s, indent + "  ", v.cur_yaw);
    s << indent << "cur_joint[]" << std::endl;
    for (size_t i = 0; i < v.cur_joint.size(); ++i)
    {
      s << indent << "  cur_joint[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.cur_joint[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // PIPER_MSGS_SRVS_MESSAGE_PIPER_CMDRESPONSE_H
