// Generated by gencpp from file piper_msgs_srvs/piper_cmd.msg
// DO NOT EDIT!


#ifndef PIPER_MSGS_SRVS_MESSAGE_PIPER_CMD_H
#define PIPER_MSGS_SRVS_MESSAGE_PIPER_CMD_H

#include <ros/service_traits.h>


#include <piper_msgs_srvs/piper_cmdRequest.h>
#include <piper_msgs_srvs/piper_cmdResponse.h>


namespace piper_msgs_srvs
{

struct piper_cmd
{

typedef piper_cmdRequest Request;
typedef piper_cmdResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct piper_cmd
} // namespace piper_msgs_srvs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::piper_msgs_srvs::piper_cmd > {
  static const char* value()
  {
    return "ab876838156246ec2905cd94b5756b0a";
  }

  static const char* value(const ::piper_msgs_srvs::piper_cmd&) { return value(); }
};

template<>
struct DataType< ::piper_msgs_srvs::piper_cmd > {
  static const char* value()
  {
    return "piper_msgs_srvs/piper_cmd";
  }

  static const char* value(const ::piper_msgs_srvs::piper_cmd&) { return value(); }
};


// service_traits::MD5Sum< ::piper_msgs_srvs::piper_cmdRequest> should match
// service_traits::MD5Sum< ::piper_msgs_srvs::piper_cmd >
template<>
struct MD5Sum< ::piper_msgs_srvs::piper_cmdRequest>
{
  static const char* value()
  {
    return MD5Sum< ::piper_msgs_srvs::piper_cmd >::value();
  }
  static const char* value(const ::piper_msgs_srvs::piper_cmdRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::piper_msgs_srvs::piper_cmdRequest> should match
// service_traits::DataType< ::piper_msgs_srvs::piper_cmd >
template<>
struct DataType< ::piper_msgs_srvs::piper_cmdRequest>
{
  static const char* value()
  {
    return DataType< ::piper_msgs_srvs::piper_cmd >::value();
  }
  static const char* value(const ::piper_msgs_srvs::piper_cmdRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::piper_msgs_srvs::piper_cmdResponse> should match
// service_traits::MD5Sum< ::piper_msgs_srvs::piper_cmd >
template<>
struct MD5Sum< ::piper_msgs_srvs::piper_cmdResponse>
{
  static const char* value()
  {
    return MD5Sum< ::piper_msgs_srvs::piper_cmd >::value();
  }
  static const char* value(const ::piper_msgs_srvs::piper_cmdResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::piper_msgs_srvs::piper_cmdResponse> should match
// service_traits::DataType< ::piper_msgs_srvs::piper_cmd >
template<>
struct DataType< ::piper_msgs_srvs::piper_cmdResponse>
{
  static const char* value()
  {
    return DataType< ::piper_msgs_srvs::piper_cmd >::value();
  }
  static const char* value(const ::piper_msgs_srvs::piper_cmdResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // PIPER_MSGS_SRVS_MESSAGE_PIPER_CMD_H
