// Generated by gencpp from file piper_msgs_srvs/piper_cmdRequest.msg
// DO NOT EDIT!


#ifndef PIPER_MSGS_SRVS_MESSAGE_PIPER_CMDREQUEST_H
#define PIPER_MSGS_SRVS_MESSAGE_PIPER_CMDREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace piper_msgs_srvs
{
template <class ContainerAllocator>
struct piper_cmdRequest_
{
  typedef piper_cmdRequest_<ContainerAllocator> Type;

  piper_cmdRequest_()
    : command()
    , param1()
    , param2()
    , param3()
    , x(0.0)
    , y(0.0)
    , z(0.0)
    , roll(0.0)
    , pitch(0.0)
    , yaw(0.0)  {
    }
  piper_cmdRequest_(const ContainerAllocator& _alloc)
    : command(_alloc)
    , param1(_alloc)
    , param2(_alloc)
    , param3(_alloc)
    , x(0.0)
    , y(0.0)
    , z(0.0)
    , roll(0.0)
    , pitch(0.0)
    , yaw(0.0)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _command_type;
  _command_type command;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _param1_type;
  _param1_type param1;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _param2_type;
  _param2_type param2;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _param3_type;
  _param3_type param3;

   typedef double _x_type;
  _x_type x;

   typedef double _y_type;
  _y_type y;

   typedef double _z_type;
  _z_type z;

   typedef double _roll_type;
  _roll_type roll;

   typedef double _pitch_type;
  _pitch_type pitch;

   typedef double _yaw_type;
  _yaw_type yaw;





  typedef boost::shared_ptr< ::piper_msgs_srvs::piper_cmdRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::piper_msgs_srvs::piper_cmdRequest_<ContainerAllocator> const> ConstPtr;

}; // struct piper_cmdRequest_

typedef ::piper_msgs_srvs::piper_cmdRequest_<std::allocator<void> > piper_cmdRequest;

typedef boost::shared_ptr< ::piper_msgs_srvs::piper_cmdRequest > piper_cmdRequestPtr;
typedef boost::shared_ptr< ::piper_msgs_srvs::piper_cmdRequest const> piper_cmdRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::piper_msgs_srvs::piper_cmdRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::piper_msgs_srvs::piper_cmdRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::piper_msgs_srvs::piper_cmdRequest_<ContainerAllocator1> & lhs, const ::piper_msgs_srvs::piper_cmdRequest_<ContainerAllocator2> & rhs)
{
  return lhs.command == rhs.command &&
    lhs.param1 == rhs.param1 &&
    lhs.param2 == rhs.param2 &&
    lhs.param3 == rhs.param3 &&
    lhs.x == rhs.x &&
    lhs.y == rhs.y &&
    lhs.z == rhs.z &&
    lhs.roll == rhs.roll &&
    lhs.pitch == rhs.pitch &&
    lhs.yaw == rhs.yaw;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::piper_msgs_srvs::piper_cmdRequest_<ContainerAllocator1> & lhs, const ::piper_msgs_srvs::piper_cmdRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace piper_msgs_srvs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::piper_msgs_srvs::piper_cmdRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::piper_msgs_srvs::piper_cmdRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::piper_msgs_srvs::piper_cmdRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::piper_msgs_srvs::piper_cmdRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::piper_msgs_srvs::piper_cmdRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::piper_msgs_srvs::piper_cmdRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::piper_msgs_srvs::piper_cmdRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "e14b35af0de9d5af1d4dbee6b2e8766b";
  }

  static const char* value(const ::piper_msgs_srvs::piper_cmdRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xe14b35af0de9d5afULL;
  static const uint64_t static_value2 = 0x1d4dbee6b2e8766bULL;
};

template<class ContainerAllocator>
struct DataType< ::piper_msgs_srvs::piper_cmdRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "piper_msgs_srvs/piper_cmdRequest";
  }

  static const char* value(const ::piper_msgs_srvs::piper_cmdRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::piper_msgs_srvs::piper_cmdRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# 请求部分\n"
"string command      # 命令\n"
"string param1       # 参数1: 备用参数\n"
"string param2       # 参数2: 备用参数\n"
"string param3       # 参数3: 备用参数\n"
"float64 x           # 目标位置x坐标\n"
"float64 y           # 目标位置y坐标\n"
"float64 z           # 目标位置z坐标\n"
"float64 roll        # 目标姿态roll角\n"
"float64 pitch       # 目标姿态pitch角\n"
"float64 yaw         # 目标姿态yaw角\n"
;
  }

  static const char* value(const ::piper_msgs_srvs::piper_cmdRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::piper_msgs_srvs::piper_cmdRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.command);
      stream.next(m.param1);
      stream.next(m.param2);
      stream.next(m.param3);
      stream.next(m.x);
      stream.next(m.y);
      stream.next(m.z);
      stream.next(m.roll);
      stream.next(m.pitch);
      stream.next(m.yaw);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct piper_cmdRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::piper_msgs_srvs::piper_cmdRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::piper_msgs_srvs::piper_cmdRequest_<ContainerAllocator>& v)
  {
    s << indent << "command: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.command);
    s << indent << "param1: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.param1);
    s << indent << "param2: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.param2);
    s << indent << "param3: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.param3);
    s << indent << "x: ";
    Printer<double>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<double>::stream(s, indent + "  ", v.y);
    s << indent << "z: ";
    Printer<double>::stream(s, indent + "  ", v.z);
    s << indent << "roll: ";
    Printer<double>::stream(s, indent + "  ", v.roll);
    s << indent << "pitch: ";
    Printer<double>::stream(s, indent + "  ", v.pitch);
    s << indent << "yaw: ";
    Printer<double>::stream(s, indent + "  ", v.yaw);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PIPER_MSGS_SRVS_MESSAGE_PIPER_CMDREQUEST_H
